#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -lt 1 ]; then
    echo "usage: $0 obj args..." >&2
    exit 1
fi

source functional-shell-mem.bash

# simply wrap around the bash function from functional-shell-mem.bash
call "$@"

