#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 1 ]; then
    echo "usage: $0 ptr" >&2
    exit 1
fi


source functional-shell-mem.bash

path=`object_path_of_type "$1" pair`

cat "$path/cdr"
