#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 2 ]; then
    echo "usage: $0 a b" >&2
    exit 1
fi


source functional-shell-mem.bash

alloc_record closure code "$1" env "$2"
