#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 0 ]; then
    {
	echo "usage: $0"
	echo "  Initializes a memory region. Needs MEM to be set to the base"
	echo "  path where the region should live."
    } >&2
    exit 1
fi


# keep in sync with functional-shell-mem.bash  !

mkdir -p "$MEM" "$MEM/"{a,b}

if [ ! -L "$MEM/cur" ]; then
    ln -s a "$MEM/cur"
fi

if [ ! -e "$MEM/id" ]; then
    echo 0 > "$MEM/id"
fi

