#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 1 ]; then
    echo "usage: $0 numberobject" >&2
    exit 1
fi


source functional-shell-mem.bash

immediateobject_echo_of_type "$1" number
