#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 1 ]; then
    echo "usage: $0 numberstring" >&2
    exit 1
fi

str="$1"


source functional-shell-mem.bash


make_object number "$1"
