#!/bin/bash

set -euo pipefail
IFS=""

args=($@)

source functional-shell-mem.bash

cont () {
    object=$1
    path=$2

    paths=()
    for obj in ${args[@]}; do
	paths+=(`object_path_of_type $obj string`)
    done

    cat ${paths[@]} > "$path"

    echo $object
}

alloc_file string cont

