#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

if [ $# -ne 1 ]; then
    echo "usage: $0 box" >&2
    exit 1
fi

box=$1


source functional-shell-mem.bash

path=`object_path_of_type "$box" box`

v=$(< "$path")

echo "$v"
